// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package w25q128jw_controller_reg_pkg;

  // Address widths within the block
  parameter int BlockAw = 6;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {logic q;} w25q128jw_controller_reg2hw_intr_state_reg_t;

  typedef struct packed {logic q;} w25q128jw_controller_reg2hw_intr_enable_reg_t;

  typedef struct packed {
    logic q;
    logic qe;
  } w25q128jw_controller_reg2hw_intr_test_reg_t;

  typedef struct packed {
    struct packed {logic q;} start;
    struct packed {logic q;} rnw;
  } w25q128jw_controller_reg2hw_control_reg_t;

  typedef struct packed {logic q;} w25q128jw_controller_reg2hw_status_reg_t;

  typedef struct packed {logic [31:0] q;} w25q128jw_controller_reg2hw_r_address_reg_t;

  typedef struct packed {logic [31:0] q;} w25q128jw_controller_reg2hw_s_address_reg_t;

  typedef struct packed {logic [31:0] q;} w25q128jw_controller_reg2hw_md_address_reg_t;

  typedef struct packed {logic [31:0] q;} w25q128jw_controller_reg2hw_length_reg_t;

  typedef struct packed {
    logic d;
    logic de;
  } w25q128jw_controller_hw2reg_intr_state_reg_t;

  typedef struct packed {
    struct packed {
      logic d;
      logic de;
    } start;
    struct packed {
      logic d;
      logic de;
    } rnw;
  } w25q128jw_controller_hw2reg_control_reg_t;

  typedef struct packed {
    logic d;
    logic de;
  } w25q128jw_controller_hw2reg_status_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } w25q128jw_controller_hw2reg_r_address_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } w25q128jw_controller_hw2reg_s_address_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } w25q128jw_controller_hw2reg_md_address_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } w25q128jw_controller_hw2reg_length_reg_t;

  // Register -> HW type
  typedef struct packed {
    w25q128jw_controller_reg2hw_intr_state_reg_t intr_state;  // [134:134]
    w25q128jw_controller_reg2hw_intr_enable_reg_t intr_enable;  // [133:133]
    w25q128jw_controller_reg2hw_intr_test_reg_t intr_test;  // [132:131]
    w25q128jw_controller_reg2hw_control_reg_t control;  // [130:129]
    w25q128jw_controller_reg2hw_status_reg_t status;  // [128:128]
    w25q128jw_controller_reg2hw_r_address_reg_t r_address;  // [127:96]
    w25q128jw_controller_reg2hw_s_address_reg_t s_address;  // [95:64]
    w25q128jw_controller_reg2hw_md_address_reg_t md_address;  // [63:32]
    w25q128jw_controller_reg2hw_length_reg_t length;  // [31:0]
  } w25q128jw_controller_reg2hw_t;

  // HW -> register type
  typedef struct packed {
    w25q128jw_controller_hw2reg_intr_state_reg_t intr_state;  // [139:138]
    w25q128jw_controller_hw2reg_control_reg_t control;  // [137:134]
    w25q128jw_controller_hw2reg_status_reg_t status;  // [133:132]
    w25q128jw_controller_hw2reg_r_address_reg_t r_address;  // [131:99]
    w25q128jw_controller_hw2reg_s_address_reg_t s_address;  // [98:66]
    w25q128jw_controller_hw2reg_md_address_reg_t md_address;  // [65:33]
    w25q128jw_controller_hw2reg_length_reg_t length;  // [32:0]
  } w25q128jw_controller_hw2reg_t;

  // Register offsets
  parameter logic [BlockAw-1:0] W25Q128JW_CONTROLLER_INTR_STATE_OFFSET = 6'h0;
  parameter logic [BlockAw-1:0] W25Q128JW_CONTROLLER_INTR_ENABLE_OFFSET = 6'h4;
  parameter logic [BlockAw-1:0] W25Q128JW_CONTROLLER_INTR_TEST_OFFSET = 6'h8;
  parameter logic [BlockAw-1:0] W25Q128JW_CONTROLLER_CONTROL_OFFSET = 6'hc;
  parameter logic [BlockAw-1:0] W25Q128JW_CONTROLLER_STATUS_OFFSET = 6'h10;
  parameter logic [BlockAw-1:0] W25Q128JW_CONTROLLER_R_ADDRESS_OFFSET = 6'h14;
  parameter logic [BlockAw-1:0] W25Q128JW_CONTROLLER_S_ADDRESS_OFFSET = 6'h18;
  parameter logic [BlockAw-1:0] W25Q128JW_CONTROLLER_MD_ADDRESS_OFFSET = 6'h1c;
  parameter logic [BlockAw-1:0] W25Q128JW_CONTROLLER_LENGTH_OFFSET = 6'h20;

  // Reset values for hwext registers and their fields
  parameter logic [0:0] W25Q128JW_CONTROLLER_INTR_TEST_RESVAL = 1'h0;
  parameter logic [0:0] W25Q128JW_CONTROLLER_INTR_TEST_W25Q128JW_CONTROLLER_EVENT_RESVAL = 1'h0;

  // Register index
  typedef enum int {
    W25Q128JW_CONTROLLER_INTR_STATE,
    W25Q128JW_CONTROLLER_INTR_ENABLE,
    W25Q128JW_CONTROLLER_INTR_TEST,
    W25Q128JW_CONTROLLER_CONTROL,
    W25Q128JW_CONTROLLER_STATUS,
    W25Q128JW_CONTROLLER_R_ADDRESS,
    W25Q128JW_CONTROLLER_S_ADDRESS,
    W25Q128JW_CONTROLLER_MD_ADDRESS,
    W25Q128JW_CONTROLLER_LENGTH
  } w25q128jw_controller_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] W25Q128JW_CONTROLLER_PERMIT[9] = '{
      4'b0001,  // index[0] W25Q128JW_CONTROLLER_INTR_STATE
      4'b0001,  // index[1] W25Q128JW_CONTROLLER_INTR_ENABLE
      4'b0001,  // index[2] W25Q128JW_CONTROLLER_INTR_TEST
      4'b0001,  // index[3] W25Q128JW_CONTROLLER_CONTROL
      4'b0001,  // index[4] W25Q128JW_CONTROLLER_STATUS
      4'b1111,  // index[5] W25Q128JW_CONTROLLER_R_ADDRESS
      4'b1111,  // index[6] W25Q128JW_CONTROLLER_S_ADDRESS
      4'b1111,  // index[7] W25Q128JW_CONTROLLER_MD_ADDRESS
      4'b1111  // index[8] W25Q128JW_CONTROLLER_LENGTH
  };

endpackage

